### ISSUE TITLE
add bcrypt to list of supported cryptography

### ISSUE THREAD

**Issue by ryanxcharles** [bitauth/libauth#10]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

Please add bcrypt support. bcrypt is actually the most useful because it is the slowest in a browser. js is so slow you probably never want to do it client-side. But if it were as fast as a server, you could do it client-side. in the case of Money Button, client-side bcrypt would let us encrypt the wallet with something strong than just the user's password. If our DB were ever hacked, every user with weak passwords could have their wallet decrypted. Client-side bcrypt is a way to mitigate that problem.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by bitjson** [comment]
Thanks for opening an issue! I'll definitely want to work on this after https://github.com/bitjson/bitcoin-ts/pull/9 👍
