### ISSUE TITLE
V2 branch: compileOutputTemplate does not respect `token`

### ISSUE THREAD

**Issue by mainnet-pat** [bitauth/libauth#102]
Hello Jason, I am exercising transaction generation involving cashtokens in v2 alpha release and stumbled upon this issue that `compileOutputTemplate` does not respect `token` field of the `outputTemplate` param at the following lines:

https://github.com/bitauth/libauth/blob/9078e67cb206ab4856e209dd02681b290236683e/src/lib/transaction/generate-transaction.ts#L73-L76
https://github.com/bitauth/libauth/blob/9078e67cb206ab4856e209dd02681b290236683e/src/lib/transaction/generate-transaction.ts#L79-L82
This leads to tokenless outputs being generated.

**Comment by mainnet-pat** [comment]
Also, `compileInputTemplate` is not respecting the token data
https://github.com/bitauth/libauth/blob/9078e67cb206ab4856e209dd02681b290236683e/src/lib/transaction/generate-transaction.ts#L108-L111

**Comment by mainnet-pat** [comment]
Also I can not find the implementation of `SIGHASH_UTXOS` signing serialization flag.

**Comment by mainnet-pat** [comment]
I see there is SIGHASH_UTXOS in unreleased code. sorry for false claim. I will try to test versus the latest tip

**Comment by mainnet-pat** [comment]
Alright! the latest head contains all necessary code for token input signing. I can send tokens now (given I add `token` in the corresponding places as indicated in the comment 1 and 2)

**Comment by bitjson** [comment]
Thanks for opening an issue @mainnet-pat! Yes, sorry that the transaction generation infrastructure is still heavily under construction. 

Please feel free to send a PR fixing any of the existing infrastructure as you find useful. Just a heads up, I'm going to have to make very deep changes in transaction generation code to support simultaneous compiling of multiple transactions by multiple entities + some other features required for proper support for decentralized application transactions. This is likely to change the TX generation API almost entirely, so you may prefer to just vendor whatever you need directly into your own library for now.

Just copying some messages below:

https://t.me/cashtoken_devs/2418:

> And just to note: we still have a long way to go on Libauth v2. The plan is to release v2 once complex decentralized applications are fully supported, and that will likely be at least 2023Q1. https://t.me/libauth_devs/29 (though a great deal of the deep refactoring is done now, so upgrading applications built with an alpha version shouldn't be too hard)

https://t.me/libauth_devs/29:

> And also, sorry for how hard it still is to create P2PKH transactions with Libauth 😆 if you have something working with another library already, I recommend you stick with that until Libauth v2 is stable. 
>
> I've made no attempt to make P2PKH wallets easier to create/use with Libauth (basically every JS library does that well already). Instead I'm working from the most advanced transactions backwards: it's very hard to take a simple P2PKH transaction construction API and make it support more complex compilations using multiple contract types, interactions between inputs/outputs, fee estimation, etc. (I think that's why we still don't have this support in any libraries 10+ years later.) But once this advanced stuff is working, I'll build some simpler P2PKH-specific "shortcut" tooling that makes P2PKH transactions as easy as other libraries.

the work left to be done - https://t.me/cashtoken_devs/1118:

> For anyone curious: the next step for this DEX is to continue building out the Libauth compiler to support this kind of multi-entity, multi-transaction compilation. When it's far enough, you should be able to simply feed it the fancy JSON object that Bitauth IDE lets you edit (the "authentication template"), and it will be able to create the transactions needed for any covenant action.
>
> Right now it would be a little more manual to make a wallet that support these contracts (the compiler can create scripts with variables filled properly, but the wallet would still have to sort of understand when it needs to use each script), but with a bit more abstraction, we'll be able to just import the template in wallets, and they'll be smart enough to "run" any action in the template (so the user picks from a list: Market Buy, Limit Sell, LP Withdrawal, etc.) For fancy covenants like this, they'll also have to get data from some DEX-specific indexer to know what the "order book" looks like and what UTXOs to spend, but the system is quite cool in that if the indexer lies to the wallet, the produced transaction for most actions will simply be invalid, so you don't necessarily have to trust your data source. (In this case, you'd want to trust your data source about current prices for market orders, but e.g. limit orders would theoretically be secure even if your indexer is malicious.)

I'm working on these changes right now, and I'll be pushing them to the v2 branch as soon as I have something to share. It's a huge effort though, so I expect it may still take me several months. I'll put out Libauth v2 betas and release candidates as soon as this refactor is done.

**Comment by bitjson** [comment]
Certainly! Could you open a PR to this repo? (I don't see it in [pull requests](https://github.com/bitauth/libauth/pulls)?)

**Comment by mainnet-pat** [comment]
Sure, please take a look a the PR I submitted just now. Hope I did everything correctly

**Comment by bitjson** [comment]
Merged, thanks! Released as `@bitauth/libauth@2.0.0-alpha.7`. 🚀
