### ISSUE TITLE
Upgrading from 1.19.1 to 2.0.0-alpha.8 issues with the import

### ISSUE THREAD

**Issue by kiok46** [bitauth/libauth#111]
```
module.exports = require("@bitauth/libauth");
                 ^
Error [ERR_REQUIRE_ESM]: require() of ES Module <path>/node_modules/@bitauth/libauth/build/main/index.js from <path>/dist/apps/rewards/main.js not supported.
Instead change the require of index.js in <your_working_dir> to a dynamic import() which is available in all CommonJS modules.
```

Any help is appreciated!

**Comment by bitjson** [comment]
Hi @kiok46 thanks for opening an issue. 

It looks like you're trying to `require()` Libauth from a CommonJS module. You'll need to at least change that to a dynamic `import()` call, but I recommend you consider upgrading your project to use ESM natively. 

Here's a good resource on the topic: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

I'm going to close this issue for now, but let me know if we should re-open.
